feat : 회원가입 (#33)
JobOasis/backend pull request #37
Opened 2024-07-25 03:10 UTC by jeongmallro

2024-08-01 07:15 UTC, thangyk requested changes

2024-08-01 07:15 UTC, thangyk commented on src/main/java/com/example/joboasis/config/RedisConfig.java
> +//    @Value("${spring.redis.host}")
@Value 설정하셔서 host랑 port 숨기는 거 왜 주석으로 바꾸신 걸까요?

2024-08-01 07:15 UTC, thangyk commented on src/main/java/com/example/joboasis/config/SecurityConfig.java
> +    }
SecurityFilterChain 설정 부분도 최근에 새로 나온 버전이 있고 지금 하신 버전이 사라지는 버전 아닌가요?

2024-08-01 07:15 UTC, thangyk commented on src/main/java/com/example/joboasis/domain/member/entity/Member.java
> +	private MemberJob job;
@Enumerated 추가하면 좋을 것 같습니다

2024-08-02 08:54 UTC, jeongmallro commented on src/main/java/com/example/joboasis/config/RedisConfig.java
> +//    @Value("${spring.redis.host}")
아 깃허브 액션 ci 부분에서 오류가 나서 잠시 주석 처리했습니다. 다시 원래대로 고쳤습니다!

2024-08-02 09:10 UTC, jeongmallro commented on src/main/java/com/example/joboasis/domain/member/entity/Member.java
> +	private MemberJob job;
@Enumerated(EnumType.STRING) 추가했습니다.

2024-08-03 06:38 UTC, jeongmallro commented on src/main/java/com/example/joboasis/config/SecurityConfig.java
> +    }
음.. Spring Security docs 를 보긴 했었는데 ㅜㅜ 혹시 새로 나온 버전에 대한 내용을 남겨주실 수 있을까요?

2024-08-03 06:39 UTC, jeongmallro reviewed
1차 피드백 확인했습니다!

2024-08-03 08:43 UTC, thangyk requested changes

2024-08-03 08:43 UTC, thangyk commented on src/main/java/com/example/joboasis/domain/resume/entity/Resume.java
>      private ResumeStatus status;
해당 부분도 enum 어노테이션 추가하면 좋을 것 같습니다!

2024-08-03 08:44 UTC, thangyk commented on src/main/java/com/example/joboasis/config/SecurityConfig.java
> +    }
https://velog.io/@kide77/Spring-Boot-3.x-Security-%EA%B8%B0%EB%B3%B8-%EC%84%A4%EC%A0%95-%EB%B0%8F-%EB%B3%80%ED%99%94

한 번 확인해보세요!

2024-08-03 10:17 UTC, jeongmallro commented on src/main/java/com/example/joboasis/domain/resume/entity/Resume.java
>      private ResumeStatus status;
추가했습니다👍

2024-08-03 11:07 UTC, jeongmallro commented on src/main/java/com/example/joboasis/config/SecurityConfig.java
> +    }
내용 확인했습니다! http.csrf().disable() 처럼 아예 인자로 아무것도 없는 메서드가 deprecated 된다는 말인 것 같습니다. 공식 문서에서도 람다식으로 표현하는 걸 권장하고 있어서 이대로 가도 될 것 같습니다. 덕분에 한번 더 확인했습니다. 감사합니다!

2024-08-03 11:08 UTC, jeongmallro reviewed
2차 피드백 확인했습니다!

2024-08-05 13:22 UTC, thangyk approved these changes

2024-08-10 07:48 UTC, merged